---
# tasks file for multimedia
- name: "Ensure multimedia packages are installed on Fedora"
  dnf:
    name: "{{ multimedia_pkg_list }}"
    state: present
  become: true

- name: "Configure default Canon folder"
  file:
    path: "/home/{{ default_user }}/Pictures/Canon"
    mode: 0755
    state: directory

- name: "Configure default Nikon folder"
  file:
    path: "/home/{{ default_user }}/Pictures/Nikon"
    mode: 0755
    state: directory
