---
- name: Configure laptop with standard tooling
  hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: Pre tasks section
      assert:
        that:
          - ansible_facts['distribution'] == 'Fedora'
        fail_msg: "This playbook can be used only on Fedora machines."
        success_msg: "Distribution check passed"

  roles:
    - base
    - virtualization
    - runtimes
    - utilities
    - dev_tools
    - containers
    - multimedia
    - dotfiles

  tasks:
    - name: "Print completion message"
      debug:
        msg: "Laptop provisioning completed"

