---
# The default user for this laptop
default_user: gbsalinetti

# Enable rpmfusion free repos
enable_rpmfusion: true

base_pkg_list:
  - vim
  - git
  - flatpak
  - NetworkManager-openvpn-gnome
  - setroubleshoot-server
  - fedora-workstation-repositories

# The list of utilities managed by yum/dnf
utilities_pkg_list:
  - git
  - tig
  - tmate
  - rclone
  - alacritty
  - fish
  - tmate
  - telegram-desktop
  - google-chrome-stable
  - keepassx
  - pass
  - pass-otp
  - tcpdump
  - wireshark
  - restic
  - sysstat
  - bcc-tools
  - jq
  - tuned
  - tuned-gtk
  - fuse-exfat
  - exfat-utils
  - pcp
  - pcp-gui
  - pcp-system-tools
  - pcp-pmda-podman
  - pcp-pmda-docker
  - libpcap
  - libpcap-devel
  - terraform

cloud_utils_pkg_list:
  - google-cloud-sdk
  - awscli

# The list of virtualization packages managed by dnf/yum
virtualization_pkg_list:
  - virt-install
  - libvirt-daemon
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - qemu-kvm
  - virt-manager
  - virt-viewer
  - libguestfs-tools
  - python3-libguestfs
  - virt-top

# The list of container tools
container_tools_pkg_list:
  - podman
  - buildah
  - skopeo

# Enable/disable minikube setup
setup_minikube: false

# The list of runtimes managed by yum/dnf
runtimes_pkg_list:
  - golang
  - java-11-openjdk.x86_64
  - java-11-openjdk-devel
  - rust
  - cargo
  - glibc-static

# The list of multimedia utilities managed by yum/dnf
multimedia_pkg_list:
  - gimp
  - darktable
  - raw-thumbnailer
  - ufraw
  - vlc

# GPG key and repo url for Microsoft VSCode
vscode_key_url: https://packages.microsoft.com/keys/microsoft.asc
vscode_repo_url: https://packages.microsoft.com/yumrepos/vscode

# The list of development tools managed by yum/dnf
devtools_pkg_list:
  - code
  - maven
  - vagrant

# The list of development tools managed as package groups
devtools_group_pkg_list:
  - '@Development Tools'
  - '@C Development Tools and Libraries'
  - '@Development Libraries'

# Dotfiles repository
dotfiles_repo: "git@github.com:giannisalinetti/dotfiles.git"
