---
# tasks file for containers
- name: "Configure container tools on Fedora"
  dnf:
    name: "{{ container_tools_pkg_list }}"
    state: present
  become: true
  when: (ansible_facts['distribution'] == 'Fedora') and (ansible_facts['distribution_version'] | int >= 30)

- name: "Install Docker package in Fedora releases prior to 31"
  dnf:
    name: docker
    state: present
  become: true
  when: 
    - ansible_facts['distribution'] == 'Fedora'
    - ansible_facts['distribution_version'] | int < 31
    - "'docker' in container_tools_pkg_list"
  
- name: "Configure container tools on RHEL"
  yum:
    name: "{{ container_tools_pkg_list }}"
    state: present
  become: true
  when: (ansible_facts['distribution'] == 'RedHat') and (ansible_facts['distribution_version'] | int >= 7)
  
- name: "Template out registries configuration for Podman"
  template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: 0644
  become: true

- name: "Collect package facts"
  package_facts:
    manager: auto

- name: "Include minikube configuration tasks"
  include_tasks: minikube.yml
  when: 
    - setup_minikube
    - '"libvirt-daemon" in ansible_facts.packages'
