---
# tasks file for containers
- name: "Configure container tools on Fedora"
  dnf:
    name: "{{ container_tools_pkg_list }}"
    state: present
  become: true
  
- name: "Template out registries configuration for Podman"
  template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
    mode: 0644
  become: true

- name: "Collect package facts"
  package_facts:
    manager: auto

- name: "Include minikube configuration tasks"
  include_tasks: minikube.yml
  when: 
    - setup_minikube
    - '"libvirt-daemon" in ansible_facts.packages'
