---
# tasks file for virtualization
- name: "Configure virtualization packages for Fedora"
  dnf:
    name: "{{ virtualization_pkg_list }}"
    state: present
  become: true

- name: "Collect package facts"
  package_facts:
    manager: auto

- name: "Ensure libvirtd service is started and enabled"
  service:
    name: libvirtd
    state: started
    enabled: true
  become: true
  when: '"libvirt-daemon" in ansible_facts.packages'

