- name: "Ensure AWS CLI package is installed on Fedora"
  dnf:
    name: awscli
    state: present
  become: true
  when: (ansible_facts['distribution'] == 'Fedora') and (ansible_facts['distribution_version'] | int >= 30)
