---
# tasks file for utilities
- name: "RPM Fusion repos are configured on Fedora"
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true
  when: 
    - enable_rpmfusion
    - ansible_facts['distribution'] == 'Fedora'

- name: "Include Terraform configuration"
  include_tasks: terraform.yml
  when: "'terraform' in utilities_pkg_list"

- name: "Include Google Cloud SDK latest packages"
  include_tasks: gcloud.yml
  when: "'google-cloud-sdk' in cloud_utils_pkg_list"

- name: "Configure basic tools and utilities"
  dnf:
    name: "{{ utilities_pkg_list }}"
    state: present
  become: true

- name: "Include Restic configurations"
  include_tasks: restic.yml
  when: "'restic' in utilities_pkg_list"

- name: "Ensure Tuned service is started and enabled"
  service:
    name: tuned
    state: started
    enabled: true
  become: true
  when: "'tuned' in utilities_pkg_list"
