---
- name: "Confiugure base system packages"
  dnf:
    name: "{{ base_pkg_list }}"
    state: present
  become: true
  when: (ansible_facts['distribution'] == 'Fedora') and (ansible_facts['distribution_version'] | int >= 30)

- name: "Enable Google Chrome repository"
  command: dnf config-manager --set-enabled google-chrome
  become: true
  when: (ansible_facts['distribution'] == 'Fedora') and (ansible_facts['distribution_version'] | int >= 30)

